### ISSUE TITLE
Parcel 1.8.1 Cannot read property 'package' of undefined

### ISSUE THREAD

**Issue by swift1911** [cyyyu/parcel-plugin-sw-precache#6]
When i update to Parcel-bundle 1.8.1 and compile error:  

Cannot read property 'package' of undefined
    at Bundler.bundler.on (/Users/swift/dev/element-starter/node_modules/parcel-plugin-sw-precache/index.js:16:43)
    at emitOne (events.js:116:13)
    at Bundler.emit (events.js:211:7)
    at Bundler.bundle (/Users/swift/dev/element-starter/node_modules/parcel-bundler/src/Bundler.js:288:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by cyyyu** [comment]
this is closed automatically by merging the related pr, but things are not fully done yet. 

after I have done the rest fixes I will patch a new version. say 0.5.0 for now.

**Comment by cyyyu** [comment]
@swift1911 try out v0.5.1
